# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from suggestions import suggestions_pb2 as suggestions_dot_suggestions__pb2


class SuggestionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSuggestions = channel.unary_unary(
                '/suggestions.SuggestionService/GetSuggestions',
                request_serializer=suggestions_dot_suggestions__pb2.GetSuggestionsRequest.SerializeToString,
                response_deserializer=suggestions_dot_suggestions__pb2.GetSuggestionsResponse.FromString,
                )


class SuggestionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSuggestions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSuggestions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSuggestions,
                    request_deserializer=suggestions_dot_suggestions__pb2.GetSuggestionsRequest.FromString,
                    response_serializer=suggestions_dot_suggestions__pb2.GetSuggestionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'suggestions.SuggestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SuggestionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSuggestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suggestions.SuggestionService/GetSuggestions',
            suggestions_dot_suggestions__pb2.GetSuggestionsRequest.SerializeToString,
            suggestions_dot_suggestions__pb2.GetSuggestionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
