# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions/suggestions.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsuggestions/suggestions.proto\x12\x0bsuggestions\"%\n\x15GetSuggestionsRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"C\n\x16GetSuggestionsResponse\x12)\n\x0esuggestedBooks\x18\x01 \x03(\x0b\x32\x11.suggestions.Book\"\x15\n\x04\x42ook\x12\r\n\x05title\x18\x01 \x01(\t2n\n\x11SuggestionService\x12Y\n\x0eGetSuggestions\x12\".suggestions.GetSuggestionsRequest\x1a#.suggestions.GetSuggestionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions.suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETSUGGESTIONSREQUEST']._serialized_start=46
  _globals['_GETSUGGESTIONSREQUEST']._serialized_end=83
  _globals['_GETSUGGESTIONSRESPONSE']._serialized_start=85
  _globals['_GETSUGGESTIONSRESPONSE']._serialized_end=152
  _globals['_BOOK']._serialized_start=154
  _globals['_BOOK']._serialized_end=175
  _globals['_SUGGESTIONSERVICE']._serialized_start=177
  _globals['_SUGGESTIONSERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
