# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection/fraud_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%fraud_detection/fraud_detection.proto\x12\x0f\x66raud_detection\"%\n\x15\x46raudDetectionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\")\n\x16\x46raudDetectionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32w\n\x15\x46raudDetectionService\x12^\n\x0b\x44\x65tectFraud\x12&.fraud_detection.FraudDetectionRequest\x1a\'.fraud_detection.FraudDetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection.fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAUDDETECTIONREQUEST']._serialized_start=58
  _globals['_FRAUDDETECTIONREQUEST']._serialized_end=95
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=97
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=138
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=140
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
