# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification/transaction_verification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7transaction_verification/transaction_verification.proto\x12\x18transaction_verification\",\n\x1eTransactionVerificationRequest\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\x1fTransactionVerificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xab\x01\n\x1eTransactionVerificationService\x12\x88\x01\n\x11VerifyTransaction\x12\x38.transaction_verification.TransactionVerificationRequest\x1a\x39.transaction_verification.TransactionVerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification.transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_start=85
  _globals['_TRANSACTIONVERIFICATIONREQUEST']._serialized_end=129
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_start=131
  _globals['_TRANSACTIONVERIFICATIONRESPONSE']._serialized_end=181
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=184
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
